[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.11.0"
prost = "0.12.4"
tokio = {version = "1.37.0", features = ["full"]}
spiceai = "2.0.0"

[build-dependencies]
tonic-build = "0.11.0"

[[bin]]
name = "agent-server"
path = "src/server.rs"