volumes:
  postgres-data:

services:
  postgres:
    image: postgres:latest
    env_file: .env.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432

  backend:
    container_name: backend-dev
    build:
      context: .
      target: dev
    restart: always
    command: npm run dev:migrate
    ports:
      - '3000:3000'
    env_file:
      - .env.dev
    depends_on:
      - postgres
    volumes:
      - /app/.next
