// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: agent_service.proto

package agent_client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TestAgent_TestMethod_FullMethodName = "/agent.TestAgent/TestMethod"
)

// TestAgentClient is the client API for TestAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestAgentClient interface {
	TestMethod(ctx context.Context, in *TestMethodRequest, opts ...grpc.CallOption) (*TestMethodResponse, error)
}

type testAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewTestAgentClient(cc grpc.ClientConnInterface) TestAgentClient {
	return &testAgentClient{cc}
}

func (c *testAgentClient) TestMethod(ctx context.Context, in *TestMethodRequest, opts ...grpc.CallOption) (*TestMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestMethodResponse)
	err := c.cc.Invoke(ctx, TestAgent_TestMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestAgentServer is the server API for TestAgent service.
// All implementations must embed UnimplementedTestAgentServer
// for forward compatibility.
type TestAgentServer interface {
	TestMethod(context.Context, *TestMethodRequest) (*TestMethodResponse, error)
	mustEmbedUnimplementedTestAgentServer()
}

// UnimplementedTestAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTestAgentServer struct{}

func (UnimplementedTestAgentServer) TestMethod(context.Context, *TestMethodRequest) (*TestMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestMethod not implemented")
}
func (UnimplementedTestAgentServer) mustEmbedUnimplementedTestAgentServer() {}
func (UnimplementedTestAgentServer) testEmbeddedByValue()                   {}

// UnsafeTestAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestAgentServer will
// result in compilation errors.
type UnsafeTestAgentServer interface {
	mustEmbedUnimplementedTestAgentServer()
}

func RegisterTestAgentServer(s grpc.ServiceRegistrar, srv TestAgentServer) {
	// If the following call pancis, it indicates UnimplementedTestAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TestAgent_ServiceDesc, srv)
}

func _TestAgent_TestMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestAgentServer).TestMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestAgent_TestMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestAgentServer).TestMethod(ctx, req.(*TestMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TestAgent_ServiceDesc is the grpc.ServiceDesc for TestAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.TestAgent",
	HandlerType: (*TestAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestMethod",
			Handler:    _TestAgent_TestMethod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent_service.proto",
}
