name: Build and Test Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./backend

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Clone respository
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 23

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build codebase
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Clean install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run tests
        run: npm test
