name: Build and Test Backend

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 23
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Install prisma
        run: npx prisma generate
      - name: Build codebase
        run: npm run build

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 23
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run tests
        run: npm test
