name: Lint Frontend

on:
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'

defaults:
  run:
    working-directory: ./frontend

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 23
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Lint codebase
        run: npm run lint
