name: Run ESLint

on:
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./backend

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 23
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Lint code base
        run: npm run lint
